function f = periodicTestFunction_1D()
% periodicTestFunction_1D generates the second one-dimension test function,
% whose continuous version is periodic on the interval [0,1]. The output of
% the function is a function handle to a piecewise function defined
% symbolically.

syms f(t)
f(t) = piecewise(0 < t <= 1/4, sin(8*pi*t),...
    1/4 < t <= 1/3, 0,...
    1/3 < t <= 3/8, 24*(t - 1/3),...
    3/8 < t <= 5/8, 1,...
    5/8 < t <= 2/3, -24*(t - 2/3),...
    2/3 < t <= 3/4, 0,...
    3/4 < t <= 1, sin(8*pi*(t - 3/4)),...
    0);

end
