%% save_Data.m
% Called by AdaptiveWindowedRegularization.m to save generated data.

if rangeSNR == 0 && P ~= 1
    save(['v',num2str(v),'_','SNR',num2str(lSNR),'_',typeChar,num2str(P),...
        '_',penaltyChar],'alpha','alphaBig','err','errBig_T','errBig_V',...
        'errBig_V2','SNR','SNRBig_T','SNRBig_V','SNRBig_V2','Xt','Dt',...
        'Xv','Dv','Dv2','x0','lb','ub','W','delta','delta2','lambda',...
        'Rvec','Rt','Rv')
elseif rangeSNR == 0 && P == 1
    save(['v',num2str(v),'_','SNR',num2str(lSNR),'_',penaltyChar],'alpha',...
        'alphaBig','err','errBig_T','errBig_V','errBig_V2','SNR',...
        'SNRBig_T','SNRBig_V','SNRBig_V2','Xt','Dt','Xv','Dv','Dv2',...
        'x0','lb','ub','W','delta','delta2','lambda','Rvec','Rt','Rv')
elseif rangeSNR ~= 0 && P == 1
    save(['v',num2str(v),'_','SNR',num2str(lSNR),'-',num2str(uSNR),'_',...
        penaltyChar],'alpha','alphaBig','err','errBig_T','errBig_V',...
        'errBig_V2','SNR','SNRBig_T','SNRBig_V','SNRBig_V2','Xt','Dt',...
        'Xv','Dv','Dv2','x0','lb','ub','W','delta','delta2','lambda',...
        'Rvec','Rt','Rv')
else
    save(['v',num2str(v),'_','SNR',num2str(lSNR),'-',num2str(uSNR),'_',...
        typeChar,num2str(P),'_',penaltyChar],'alpha','alphaBig','err',...
        'errBig_T','errBig_V','errBig_V2','SNR','SNRBig_T','SNRBig_V',...
        'SNRBig_V2','Xt','Dt','Xv','Dv','Dv2','x0','lb','ub','W',...
        'delta','delta2','lambda','Rvec','Rt','Rv')
end
clear,clc
